# Generated by Django 6.1.1 on 2026-09-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_vendedor_erp',
            field=models.CharField(blank=True, help_text='Obrigatório para usuários com perfil Vendedor. Ex: GABRIELLI', max_length=100, null=True, verbose_name='Nome do Vendedor no Hardness/ERP'),
        ),
    ]
