# Generated by Django 6.1.1 on 2026-09-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_nome_vendedor_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('VENDEDOR', 'Vendedor'), ('ALMOXARIFADO', 'Almoxarifado'), ('COMPRAS', 'Compras')], default='VENDEDOR', max_length=20, verbose_name='Perfil de Acesso'),
        ),
    ]
