# Generated by Django 6.1.1 on 2026-09-22 21:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ca', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número do CA')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('status', models.CharField(choices=[('VALIDO', 'Válido'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('SUSPENSO', 'Suspenso')], default='VALIDO', max_length=20, verbose_name='Status do CA')),
                ('fabricante', models.CharField(max_length=255, verbose_name='Fabricante / Importador')),
                ('descricao_equipamento', models.TextField(blank=True, null=True, verbose_name='Descrição do Equipamento (MTE)')),
                ('normas_atendidas', models.TextField(blank=True, null=True, verbose_name='Normas Técnicas Atendidas')),
                ('laudo_pdf', models.FileField(blank=True, null=True, upload_to='laudos_ca/', verbose_name='Arquivo do Laudo / Ficha Técnica')),
                ('ultima_consulta_api', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização via API')),
            ],
            options={
                'verbose_name': 'Certificado de Aprovação (CA)',
                'verbose_name_plural': 'Certificados de Aprovação (CA)',
                'ordering': ['numero_ca'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / Código Interno')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('tamanho_variacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamanho / Variação (ex: G, 42, Único)')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('PAR', 'Par'), ('CJ', 'Conjunto'), ('CX', 'Caixa'), ('PCT', 'Pacote')], default='UN', max_length=5, verbose_name='Unidade de Medida')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço de Venda')),
                ('estoque_atual', models.PositiveIntegerField(default=0, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo de Segurança')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo para Venda')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='inventory.certificadoaprovacao', verbose_name='Certificado de Aprovação (CA)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='inventory.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto EPI',
                'verbose_name_plural': 'Produtos EPIs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra / Devolução)'), ('SAIDA', 'Saída (Venda / Descarte)'), ('AJUSTE', 'Ajuste de Balanço / Inventário')], max_length=10, verbose_name='Tipo de Movimento')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Movimentada')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo / Observação')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventory.produtoepi', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_hora'],
            },
        ),
    ]
