# Generated by Django 6.1.1 on 2026-09-27 13:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoepi',
            name='data_ultima_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Última Entrada (ERP)'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='data_ultima_saida',
            field=models.DateField(blank=True, null=True, verbose_name='Última Venda (ERP)'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='estoque_fisico',
            field=models.IntegerField(default=0, verbose_name='Estoque Físico + Fora'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='estoque_maximo',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque Máximo (0 = Automático)'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='item_critico',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Item Crítico (Não Pode Faltar)'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='marca',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Marca / Fabricante'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='nao_comprar_erp',
            field=models.BooleanField(default=False, verbose_name='Bloqueado p/ Compra (ERP)'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='qtd_ordem_compra',
            field=models.IntegerField(default=0, verbose_name='Qtd em Ordem de Compra (OC)'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='inventory.certificadoaprovacao', verbose_name='Certificado de Aprovação (CA)'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='estoque_atual',
            field=models.IntegerField(default=0, verbose_name='Estoque Líquido + Fora'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo de Segurança'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='preco_custo',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12, verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='preco_venda',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12, verbose_name='Preço de Venda'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU / Código Interno'),
        ),
        migrations.AlterField(
            model_name='produtoepi',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('PAR', 'Par'), ('PC', 'Peça'), ('CJ', 'Conjunto'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('RL', 'Rolo'), ('KG', 'Quilograma'), ('MT', 'Metro')], default='UN', max_length=10, verbose_name='Unidade de Medida'),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item_erp', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='ID Item (Empresa-T008_Id)')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('numero_nota', models.CharField(db_index=True, max_length=50, verbose_name='Número da NF')),
                ('data_emissao', models.DateField(db_index=True, verbose_name='Data de Emissão')),
                ('cliente_nome', models.CharField(db_index=True, max_length=255, verbose_name='Cliente / Razão Social')),
                ('cliente_id_erp', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Cliente ERP')),
                ('vendedor_nome', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Vendedor')),
                ('codigo_produto', models.CharField(db_index=True, max_length=50, verbose_name='Código do Produto (SKU)')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('unidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade')),
                ('cfop', models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Unitário')),
                ('valor_custo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12, verbose_name='Custo Unitário na Venda')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total')),
                ('data_sincronizacao', models.DateTimeField(auto_now=True, verbose_name='Última Sincronização')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='inventory.produtoepi', verbose_name='Produto Vinculado')),
            ],
            options={
                'verbose_name': 'Item de Venda (NF)',
                'verbose_name_plural': 'Itens de Venda (NF)',
                'ordering': ['-data_emissao', '-numero_nota'],
                'indexes': [models.Index(fields=['data_emissao', 'codigo_produto'], name='inventory_i_data_em_5f2af7_idx'), models.Index(fields=['cliente_nome', 'codigo_produto'], name='inventory_i_cliente_1f0591_idx')],
            },
        ),
    ]
