# Generated by Django 6.1.1 on 2026-09-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_produtoepi_data_ultima_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoaprovacao',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
    ]
