# Generated by Django 6.1.1 on 2026-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_certificadoaprovacao_data_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoepi',
            name='editado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Cadastro Editado Manualmente'),
        ),
        migrations.AddField(
            model_name='produtoepi',
            name='subcategoria',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Subcategoria'),
        ),
    ]
