# Generated by Django 6.1.1 on 2026-09-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('numero_nota', models.CharField(max_length=50, unique=True, verbose_name='Número da NF')),
                ('serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Série')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente / Razão Social')),
                ('cliente_documento', models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ/CPF')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total')),
                ('cfop', models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('dados_brutos', models.JSONField(blank=True, null=True, verbose_name='Payload Bruto')),
                ('data_sincronizacao', models.DateTimeField(auto_now=True, verbose_name='Última Sincronização')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao', '-numero_nota'],
            },
        ),
    ]
