# Generated by Django 6.1.1 on 2026-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='vendedor_nome',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Vendedor'),
        ),
    ]
