# Generated by Django 6.1.1 on 2026-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_notafiscal_vendedor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_nome', models.CharField(db_index=True, max_length=100, verbose_name='Vendedor / Empresa')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês (1-12)')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor da Meta (R$)')),
                ('titulo_meta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título / Descrição da Meta')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Meta de Vendedor',
                'verbose_name_plural': 'Metas de Vendedores',
                'ordering': ['-ano', '-mes', 'vendedor_nome'],
                'unique_together': {('vendedor_nome', 'mes', 'ano')},
            },
        ),
    ]
