# Generated by Django 6.1.1 on 2026-09-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_metavendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hardness', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome no Hardness (ERP)')),
                ('nome_piperun', models.CharField(blank=True, help_text='Se vazio, o sistema tentará o vínculo automático na próxima sincronização.', max_length=100, null=True, verbose_name='Nome no PipeRun (CRM)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Dashboard')),
            ],
            options={
                'verbose_name': 'Vendedor (Vínculo)',
                'verbose_name_plural': 'Vendedores (Vínculos)',
                'ordering': ['nome_hardness'],
            },
        ),
    ]
