# Generated by Django 6.1.1 on 2026-09-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ativo_ranking',
            field=models.BooleanField(default=True, verbose_name='Ativo no Ranking'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo no Dashboard (Seletor)'),
        ),
    ]
