# Generated by Django 6.1.1 on 2026-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_vendedor_ativo_ranking_alter_vendedor_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTAS_HARDNESS', 'Notas Fiscais (Hardness)'), ('ESTOQUE_HARDNESS', 'Estoque & Itens (Hardness)'), ('METAS_PIPERUN', 'Metas de Vendas (PipeRun)'), ('CONSULTA_CA', 'Vencimentos de CA (MTE)'), ('COMPLETA', 'Sincronização Completa')], db_index=True, max_length=30, verbose_name='Tipo de Sincronização')),
                ('origem', models.CharField(choices=[('MANUAL_PAINEL', 'Painel Web (Manual)'), ('AGENDADOR_AUTO', 'Agendador Automático'), ('CLI', 'Comando de Terminal (CLI)')], default='MANUAL_PAINEL', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro / Falha')], db_index=True, default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('usuario', models.CharField(default='Sistema', max_length=100, verbose_name='Disparado por')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('duracao_segundos', models.FloatField(default=0.0, verbose_name='Duração (s)')),
                ('registros_criados', models.IntegerField(default=0, verbose_name='Registros Criados')),
                ('registros_atualizados', models.IntegerField(default=0, verbose_name='Registros Atualizados')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Resumo / Detalhes')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
