# Generated by Django 6.1.1 on 2026-09-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_logsincronizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='cliente_documento',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='data_emissao',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero_nota',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Número da NF'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('empresa', 'numero_nota')},
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['status', 'data_emissao'], name='sales_notaf_status_990ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['vendedor_nome', 'data_emissao'], name='sales_notaf_vendedo_b46485_idx'),
        ),
    ]
