# Generated by Django 6.1.1 on 2026-09-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_logsincronizacao_tipo_contapagar_contareceber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_chave', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Conta (Subconta / Grupo ERP)')),
                ('grupo_conta_erp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Grupo de Conta ERP')),
                ('centro_custo_erp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Centro de Custo ERP')),
                ('categoria', models.CharField(db_index=True, max_length=100, verbose_name='Categoria Gerencial')),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategoria')),
                ('tipo_custo', models.CharField(choices=[('CMV', 'A. Custo de Mercadorias / CMV'), ('FIXO', 'B. Custos Fixos'), ('VARIAVEL', 'C. Custos Variáveis'), ('FINANCEIRO', 'D. Despesas Financeiras'), ('EXTRAORDINARIO', 'E. Despesas Extraordinárias')], db_index=True, default='FIXO', max_length=30, verbose_name='Tipo de Custo')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Custo Fixo Recorrente')),
                ('editado_manualmente', models.BooleanField(default=False, verbose_name='Editado pela Gestão')),
                ('atualizado_por', models.CharField(blank=True, default='Sistema', max_length=100, null=True, verbose_name='Atualizado por')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Classificação de Custo',
                'verbose_name_plural': 'Classificações de Custos',
                'ordering': ['tipo_custo', 'categoria', 'conta_chave'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_index=True, default='TODAS', max_length=100, unique=True, verbose_name='Empresa / Escopo')),
                ('saldo_bancario_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Saldo Bancário Atual Informado (R$)')),
                ('reserva_minima', models.DecimalField(decimal_places=2, default=30000.0, max_digits=14, verbose_name='Reserva Mínima Operacional (R$)')),
                ('alerta_aumento_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Alerta Aumento Relevante (%)')),
                ('alerta_aumento_valor', models.DecimalField(decimal_places=2, default=500.0, max_digits=12, verbose_name='Alerta Aumento Relevante Mínimo (R$)')),
                ('usuario_atualizacao', models.CharField(default='Sistema', max_length=100, verbose_name='Usuário Responsável pela Atualização')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Atualização')),
            ],
            options={
                'verbose_name': 'Configuração Financeira / Saldo Bancário',
                'verbose_name_plural': 'Configurações Financeiras / Saldos Bancários',
                'ordering': ['empresa'],
            },
        ),
    ]
