# Generated by Django 6.1.1 on 2026-10-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_classificacaocusto_configuracaofinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item_erp', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='ID Item (Empresa-T004_Id)')),
                ('empresa', models.CharField(db_index=True, max_length=100, verbose_name='Empresa')),
                ('numero_orcamento', models.CharField(db_index=True, max_length=50, verbose_name='Número do Orçamento (T003_Id)')),
                ('codigo_produto', models.CharField(db_index=True, max_length=50, verbose_name='Código do Produto (SKU)')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('unidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total (R$)')),
                ('data_emissao', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Emissão')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('vendedor_nome', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Vendedor')),
                ('dados_brutos', models.JSONField(blank=True, null=True, verbose_name='Payload Bruto')),
                ('data_sincronizacao', models.DateTimeField(auto_now=True, verbose_name='Última Sincronização')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sales.orcamento', verbose_name='Orçamento Vinculado')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'ordering': ['-data_emissao', '-numero_orcamento'],
                'indexes': [models.Index(fields=['data_emissao', 'codigo_produto'], name='sales_itemo_data_em_73a69f_idx'), models.Index(fields=['numero_orcamento', 'empresa'], name='sales_itemo_numero__93c90e_idx')],
            },
        ),
    ]
